# Generated by Django 5.1.3 on 2024-11-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_actor_actor_biography_en_actor_actor_biography_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielanguages',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_languages', to='movie_app.movie'),
        ),
    ]
